### ISSUE TITLE
mzRAPP crashes

### ISSUE THREAD

**Issue by vgikas** [YasinEl/mzRAPP#21]
Hi Yassin
I have been very excited when I found out about mzRAPP and is seems like a very nice idea
But, the following issue occurs when I try to replicate the example of the vignette
After creating or loading the benchmark file (and the assigned and unassigned csv as well), it seems that the Benchmark compare step finishes succesfully, but then either the Shiny or the browser crash. The error message is found below
Loading required package: shiny

Listening on http://127.0.0.1:6386
Starting xcms aligned import
Successful xcms aligned import. No. of peaks imported: 171573
Starting xcms unaligned import
Successful xcms unaligned import. No. of peaks imported: 361693
Ignored 482 duplicated non-aligned peaks from non-targeted output (identical rt, mz and area)
Starting to compare benchmark with non-targeted output
Done!
Warning: Error in colnamesInt: argument specifying columns received non-existing column(s): cols[1]='1'
  3: runApp
  2: print.shiny.appobj
  1: <
Could you please suggest some solution?
Thank you in advance
(I am using R 4.3.2 and Rstudio 2023.12.1+402 "Ocean Storm" Release) using Windows 11

**Comment by YasinEl** [comment]
Hey should be fixed so hope it will do what you need now. Let me know if you have further problems.
Yasin

**Comment by vgikas** [comment]
Thank you really very much. It works perfectly.
Best

**Comment by vgikas** [comment]
Dear Yasin

its works like a charm. I really really thank you very much for your
effort and the fast response.

Best reagrards

E. Gikas


> Hey should be fixed so hope it will do what you need now. Let me know if
> you have further problems.
> Yasin
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/YasinEl/mzRAPP/issues/21#issuecomment-1950696987
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
E Gikas

Professor
Laboratory of Analytical Chemistry
Faculty of Chemistry
National and Kapodistrian University of Athens

**Comment by YasinEl** [comment]
Thank you for appreciating!
